class Bread {
    constructor(id, name, price, rate, desc) {
        this.id = id
        this.name = name
        this.price = price
        this.rate = rate
        this.desc = desc
    }
}

let bagel = new Bread("bgl", "Bagel", "$10.99", "5/5", "Bagel is a bread originating in the Jewish communities of Poland. It is shaped by hand into the form of a ring from yeasted wheat dough, roughly hand-sized. It is dense, chewy, doughy interior with a browned and crisp exterior. Bagels are topped with seeds baked on the outer crust.")
let baguette = new Bread("bgt", "Baguette", "$8.99", "5/5", "Baguette is a long, thin type of bread of French origin that is made from basic lean dough. It is distinguishable by its length and crisp crust.")
let breadstick = new Bread("bst", "Bread Stick", "$5.99", "5/5", "Breadstick, sometimes is called as grissini, grissino or dipping sticks, are generally pencil-sized sticks of crisp, dry baked bread that originated in Italy. These crispy sticks make the perfect appetizer or serve with a bowl of soup or stew.")
let brioche = new Bread("brc", "Brioche", "$12.99", "5/5", "Brioche is a bread of French origin and whose high egg and butter content gives it a rich and tender crumb. It has a dark, golden, and flaky crust, accentuated by an egg wash applied after proofing.")
let ciabatta = new Bread("btr", "Ciabatta", "$15.99", "5/5", "Ciabatta is an Italian white bread made from wheat flour, water, salt, yeast and olive oil, created in 1982 by a baker in Adria, Italy. Ciabatta is elongated, broad, and flat. Ciabatta is made with a strong flour and uses a much wetter dough than traditional French bread.")
let croissant = new Bread("crs", "Croissant", "$12.99", "5/5", "Croissant is a buttery, flaky, viennoiserie pastry of Austrian origin, but mostly associated with France. Croissants are named for its crescent shape and are made of a layered yeast-leavened dough. The dough is layered with butter, rolled and folded several times. The results is a layered, flaky texture, similar to a puff pastry.")
let dorayaki = new Bread("dyk", "Dorayaki", "$6.99", "5/5", "Dorayaki is a type of Japanese bread. It consists of two small pancake-like patties made from castella wrapped around a filling of sweet azuki bean paste. The original Dorayaki consisted of only one layer. Its current shape was invented in 1914. In Japanese, dora means gong, and because of the similarity of the shapes, this is probably the origin of the name of it.")
let muffin = new Bread("mfn", "Muffin", "$5.99", "5/5", "Muffin is an individual-sized, baked product. While quickbread muffins are often sweetened, there are savory varieties made with ingredients such as corn and cheese. The flatbread is of British or European derivation, and dates from at least the early 18th century, while the quickbread originated in North America during the 19th century. Both are common worldwide today.")
let pretzel = new Bread("ptz", "Pretzel", "$3.99", "5/5", "Pretzel is a type of baked pastry made from dough that is shaped into a knot. The traditional pretzel shape is a distinctive symmetrical form, with the ends of a long strip of dough intertwined and then twisted back onto itself in a particular way (a pretzel loop or pretzel bow). Today, pretzels come in a wide range of shapes.")
let wheatbread = new Bread("web", "Wheat Bread", "$17.99", "5/5", "Wheat bread is a type of bread made using flour that is entirely milled from whole wheat grains. It is one kind of brown bread. Synonyms or near-synonyms for wheat bread outside the United States are whole grain bread or wholemeal bread. Some regions of the US simply called the bread wheat bread, a comparison to white bread.")
let whitebread = new Bread("wib", "White Bread", "$15.99", "5/5", "White bread is bread made from wheat flour from which the bran and the germ layers have been removed from the whole wheatberry as part of the flour grinding or milling process, producing a light-colored flour. This milling process can give white flour a longer shelf life by removing the natural oils from the whole grain.")